### ISSUE TITLE
Error while signing the firefox add-ons

### ISSUE THREAD

**Issue by khuzama98** [kewisch/action-web-ext#19]
Can you please guide me here with this issue, I have been trying to solve this but it keeps giving me a timeout error.

`Error: Error: Signing took too long to complete; last status: {"guide":"<my-guid>","active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v5/addons/guid/versions/1.0.3/uploads/209ae4ff65894279abac119e22c100d0/","files":[{"download_url":"https://addons.mozilla.org/api/v5/file/3848030/xxx-1.0.3-an+fx.xpi","hash":"sha256:010377edd327eda45cbe4797c59e84bd2ec0e9c6761c0368c719fc3e06a75555","signed":false}],"passed_review":null,"pk":"209ae4ff65894279abac119e22c100d0","processed":true,"reviewed":null,"valid":true,"valid...`

Last time it ran for almost 6 hours and then gave the timeout error, the fact that I explored this error and find that the delay is caused by AMO and they updated the message explaining what the cause was, here is the [link](https://github.com/mozilla/web-ext/issues/2314). So I think the pipeline should not be giving error in this scenario. As the pipeline give an error I'm unable to drop the artefact for the download.

Kindly guide me here. 
Thanks

**Comment by kewisch** [comment]
I've made some changes, can you let me know if this is still an issue with v1? It should pass with a warning that the add-on was not auto-signed.

**Comment by XFox111** [comment]
Hi, I have the same issue. It ran for full 6 hours and then was stopped by Host Agent with error `The job running on runner Hosted Agent has exceeded the maximum execution time of 360 minutes`

It happened yesterday (07-Sep-22) though the last time I successfully ran the pipeline was about a year ago

Here's my part of the workflow file:
```yaml
Firefox:
    needs: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: 'Build'
        path: Build

    - name: Build Extension for Firefox
      id: web-ext-build
      uses: kewisch/action-web-ext@v1
      with:
        cmd: build
        source: Build

    - name: 'Sign & publish'
      id: web-ext-sign
      uses: kewisch/action-web-ext@v1
      with:
        cmd: sign
        channel: listed
        source: ${{ steps.web-ext-build.outputs.target }}
        apiKey: ${{ secrets.FIREFOX_API_KEY }}
        apiSecret: ${{ secrets.FIREFOX_CLIENT_SECRET }}

    - name: Drop artifacts
      uses: actions/upload-artifact@v3
      with:
        name: 'Firefox'
        path: ${{ steps.web-ext-sign.outputs.target }}
```

I can share my logs here, but I walked it through, and it doesn't seem to have any useful info
