### ISSUE TITLE
Arch dependent optional deps are not included

### ISSUE THREAD

**Issue by muffinresearch** [kewisch/action-web-ext#39]
Hi @kewisch 👋, using the[ current rev](https://github.com/kewisch/action-web-ext/commit/e9d27a55a8b266d9055e27c9814b92071c5a3dd0), I'm hitting an error running the action with the action installed as a submodule local to the repo I'm using it from:

```
Error: Cannot find module '@node-rs/crc32-linux-x64-gnu'
```

This looks to be due to the arch specific deps not being part of the committed `node_modules`. A temporary workaround is  possible by adding a step which runs `npm install` like so:

```yaml
      - name: workaround missing dep in action-web-ext
        working-directory: .github/actions/action-web-ext
        run: npm install
```
